const LOADING_GT = 'LOADING_GT'
const INITIALIZING_MODEL = 'INITIALIZING_MODEL'
const LEARNING = 'LEARNING'
const FINALIZING = 'FINALIZING'
module.exports = {
  LOADING_GT,
  INITIALIZING_MODEL,
  LEARNING,
  FINALIZING,
}

